// <auto-generated />
using System;
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(D2DContext))]
    [Migration("20260522215204_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesignerDesignProducer", b =>
                {
                    b.Property<string>("FavoritedByID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FavouriteID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoritedByID", "FavouriteID");

                    b.HasIndex("FavouriteID");

                    b.ToTable("DesignerDesignProducer");
                });

            modelBuilder.Entity("Domain.Entities.Chats.AiModel.ModelChat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("ModelChats");
                });

            modelBuilder.Entity("Domain.Entities.Chats.AiModel.ModelChatMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.Property<int>("LimitCounter")
                        .HasColumnType("int");

                    b.Property<int>("ModelChatID")
                        .HasColumnType("int");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ModelChatID");

                    b.ToTable("ModelChatMessages");
                });

            modelBuilder.Entity("Domain.Entities.Chats.Chat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdicerLimit")
                        .HasColumnType("int");

                    b.Property<int>("ProducerCount")
                        .HasColumnType("int");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Domain.Entities.Chats.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChatID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ChatID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Designers.DesignVerification", b =>
                {
                    b.Property<string>("StepUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesignerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StepUrl");

                    b.HasIndex("DesignerID");

                    b.ToTable("DesignVerifications");
                });

            modelBuilder.Entity("Domain.Entities.Designers.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsProducer")
                        .HasColumnType("bit");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DesignerID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Designs.Design", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Designs.DesignImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid?>("CustomerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProducerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CustomerDesignID");

                    b.HasIndex("DesignerDesignID");

                    b.HasIndex("ProducerDesignID");

                    b.ToTable("DesignImages");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ActiveOfferLogs", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOfferActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OfferID", "IsOfferActive");

                    b.ToTable("ActiveOfferLogs");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerOffer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfferStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProducerID");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Payment.Escrow", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EscrowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("HeldAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOfferActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProducerOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProducerOfferID");

                    b.HasIndex("CustomerOfferID", "IsOfferActive");

                    b.ToTable("Escrows");
                });

            modelBuilder.Entity("Domain.Entities.Payment.Transaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EscrowID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EscrowID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.Producers.LicenseVerification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LicenseStatus")
                        .HasColumnType("int");

                    b.Property<string>("LicenseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProducerID");

                    b.ToTable("LicenseVerifications");
                });

            modelBuilder.Entity("Domain.Entities.Producers.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationsType")
                        .HasColumnType("int");

                    b.Property<string>("RefrenceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Offer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Shared.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnnonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BD")
                        .HasColumnType("datetime2");

                    b.Property<string>("BackImageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontImageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityStatus")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ReportsCounter")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Designs.CustomerDesign", b =>
                {
                    b.HasBaseType("Domain.Entities.Designs.Design");

                    b.Property<Guid?>("CustomerPublishedOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CustomerPublishedOfferID");

                    b.ToTable("CustomerDesigns");
                });

            modelBuilder.Entity("Domain.Entities.Designs.DesignerDesign", b =>
                {
                    b.HasBaseType("Domain.Entities.Designs.Design");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("DesignerID");

                    b.ToTable("DesignerDesigns");
                });

            modelBuilder.Entity("Domain.Entities.Designs.ProducerDesign", b =>
                {
                    b.HasBaseType("Domain.Entities.Designs.Design");

                    b.Property<Guid?>("CustomerCustomOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProducerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CustomerCustomOfferID");

                    b.HasIndex("ProducerID");

                    b.ToTable("ProducerDesigns");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerCustomerOffer", b =>
                {
                    b.HasBaseType("Domain.Entities.Offers.ProducerOffer");

                    b.Property<Guid?>("CustomerCustomOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerPublishedOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CustomerCustomOfferID");

                    b.HasIndex("CustomerPublishedOfferID");

                    b.ToTable("ProducerCustomerOffers");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerDesignerOffer", b =>
                {
                    b.HasBaseType("Domain.Entities.Offers.ProducerOffer");

                    b.Property<Guid>("DesignerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("DesignerDesignID");

                    b.ToTable("ProducerDesignerOffers");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerOffer", b =>
                {
                    b.HasBaseType("Domain.Entities.Shared.Offer");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerOfferStatus")
                        .HasColumnType("int");

                    b.HasIndex("CustomerID");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.HasBaseType("Domain.Entities.Shared.User");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Entities.Designers.Designer", b =>
                {
                    b.HasBaseType("Domain.Entities.Shared.User");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("Domain.Entities.Producers.Producer", b =>
                {
                    b.HasBaseType("Domain.Entities.Shared.User");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerCustomOffer", b =>
                {
                    b.HasBaseType("Domain.Entities.Offers.CustomerOffer");

                    b.Property<Guid?>("ProducerCustomerOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProducerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProducerCustomerOfferID");

                    b.HasIndex("ProducerDesignID");

                    b.HasIndex("ID", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CustomerCustomOffer");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerPublishedOffer", b =>
                {
                    b.HasBaseType("Domain.Entities.Offers.CustomerOffer");

                    b.Property<Guid>("CustomerDesignID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CustomerDesignID");

                    b.HasIndex("ID", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CustomerPublishedOffers");
                });

            modelBuilder.Entity("DesignerDesignProducer", b =>
                {
                    b.HasOne("Domain.Entities.Producers.Producer", null)
                        .WithMany()
                        .HasForeignKey("FavoritedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Designs.DesignerDesign", null)
                        .WithMany()
                        .HasForeignKey("FavouriteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Chats.AiModel.ModelChat", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithOne("ModelChat")
                        .HasForeignKey("Domain.Entities.Chats.AiModel.ModelChat", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Chats.AiModel.ModelChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.Chats.AiModel.ModelChat", "ModelChat")
                        .WithMany("Message")
                        .HasForeignKey("ModelChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelChat");
                });

            modelBuilder.Entity("Domain.Entities.Chats.Chat", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Chats")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("Chats")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Chats.Message", b =>
                {
                    b.HasOne("Domain.Entities.Chats.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Domain.Entities.Designers.DesignVerification", b =>
                {
                    b.HasOne("Domain.Entities.Designers.Designer", "Designer")
                        .WithMany("DesignVerifications")
                        .HasForeignKey("DesignerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("Domain.Entities.Designers.Report", b =>
                {
                    b.HasOne("Domain.Entities.Designers.Designer", "Designer")
                        .WithMany("Reports")
                        .HasForeignKey("DesignerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("Reports")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Designer");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Designs.DesignImage", b =>
                {
                    b.HasOne("Domain.Entities.Designs.CustomerDesign", "CustomerDesign")
                        .WithMany("DesignImages")
                        .HasForeignKey("CustomerDesignID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Designs.DesignerDesign", "DesignerDesign")
                        .WithMany("DesignImages")
                        .HasForeignKey("DesignerDesignID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Designs.ProducerDesign", "ProducerDesign")
                        .WithMany("DesignImages")
                        .HasForeignKey("ProducerDesignID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CustomerDesign");

                    b.Navigation("DesignerDesign");

                    b.Navigation("ProducerDesign");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ActiveOfferLogs", b =>
                {
                    b.HasOne("Domain.Entities.Offers.CustomerCustomOffer", null)
                        .WithMany()
                        .HasForeignKey("OfferID", "IsOfferActive")
                        .HasPrincipalKey("ID", "IsActive")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Offers.CustomerPublishedOffer", null)
                        .WithMany()
                        .HasForeignKey("OfferID", "IsOfferActive")
                        .HasPrincipalKey("ID", "IsActive")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerOffer", b =>
                {
                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("ProducerOffers")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Payment.Escrow", b =>
                {
                    b.HasOne("Domain.Entities.Offers.ProducerOffer", "ProducerOffer")
                        .WithMany()
                        .HasForeignKey("ProducerOfferID");

                    b.HasOne("Domain.Entities.Offers.CustomerCustomOffer", null)
                        .WithMany()
                        .HasForeignKey("CustomerOfferID", "IsOfferActive")
                        .HasPrincipalKey("ID", "IsActive")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Offers.CustomerPublishedOffer", null)
                        .WithMany()
                        .HasForeignKey("CustomerOfferID", "IsOfferActive")
                        .HasPrincipalKey("ID", "IsActive")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProducerOffer");
                });

            modelBuilder.Entity("Domain.Entities.Payment.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.Payment.Escrow", "Escrow")
                        .WithMany("Transactions")
                        .HasForeignKey("EscrowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escrow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Producers.LicenseVerification", b =>
                {
                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("LicenseVerifications")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Producers.Review", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("Reviews")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Designs.CustomerDesign", b =>
                {
                    b.HasOne("Domain.Entities.Offers.CustomerPublishedOffer", "CustomerPublishedOffer")
                        .WithMany()
                        .HasForeignKey("CustomerPublishedOfferID");

                    b.Navigation("CustomerPublishedOffer");
                });

            modelBuilder.Entity("Domain.Entities.Designs.DesignerDesign", b =>
                {
                    b.HasOne("Domain.Entities.Designers.Designer", "Designer")
                        .WithMany("DesignerDesigns")
                        .HasForeignKey("DesignerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("Domain.Entities.Designs.ProducerDesign", b =>
                {
                    b.HasOne("Domain.Entities.Offers.CustomerCustomOffer", "CustomerCustomOffer")
                        .WithMany()
                        .HasForeignKey("CustomerCustomOfferID");

                    b.HasOne("Domain.Entities.Producers.Producer", "Producer")
                        .WithMany("ProducerDesigns")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerCustomOffer");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerCustomerOffer", b =>
                {
                    b.HasOne("Domain.Entities.Offers.CustomerCustomOffer", "CustomerCustomOffer")
                        .WithMany()
                        .HasForeignKey("CustomerCustomOfferID");

                    b.HasOne("Domain.Entities.Offers.CustomerPublishedOffer", "CustomerPublishedOffer")
                        .WithMany("ProducerCustomerOffers")
                        .HasForeignKey("CustomerPublishedOfferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerCustomOffer");

                    b.Navigation("CustomerPublishedOffer");
                });

            modelBuilder.Entity("Domain.Entities.Offers.ProducerDesignerOffer", b =>
                {
                    b.HasOne("Domain.Entities.Designs.DesignerDesign", "DesignerDesign")
                        .WithMany("ProducerDesignerOffers")
                        .HasForeignKey("DesignerDesignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignerDesign");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerOffer", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Offers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Customers.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Customers.Address", "Addresses", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"));

                            b1.Property<string>("AppartmentNo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CustomerID")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Goverate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Selected")
                                .HasColumnType("bit");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ID");

                            b1.HasIndex("CustomerID");

                            b1.ToTable("Addresses");

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerID");

                            b1.Navigation("Customer");
                        });

                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.Designers.Designer", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Designers.Designer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Producers.Producer", b =>
                {
                    b.HasOne("Domain.Entities.Shared.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Producers.Producer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerCustomOffer", b =>
                {
                    b.HasOne("Domain.Entities.Offers.ProducerCustomerOffer", "ProducerCustomerOffer")
                        .WithMany()
                        .HasForeignKey("ProducerCustomerOfferID");

                    b.HasOne("Domain.Entities.Designs.ProducerDesign", "ProducerDesign")
                        .WithMany()
                        .HasForeignKey("ProducerDesignID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProducerCustomerOffer");

                    b.Navigation("ProducerDesign");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerPublishedOffer", b =>
                {
                    b.HasOne("Domain.Entities.Designs.CustomerDesign", "CustomerDesign")
                        .WithMany()
                        .HasForeignKey("CustomerDesignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerDesign");
                });

            modelBuilder.Entity("Domain.Entities.Chats.AiModel.ModelChat", b =>
                {
                    b.Navigation("Message");
                });

            modelBuilder.Entity("Domain.Entities.Chats.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Payment.Escrow", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.Shared.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Designs.CustomerDesign", b =>
                {
                    b.Navigation("DesignImages");
                });

            modelBuilder.Entity("Domain.Entities.Designs.DesignerDesign", b =>
                {
                    b.Navigation("DesignImages");

                    b.Navigation("ProducerDesignerOffers");
                });

            modelBuilder.Entity("Domain.Entities.Designs.ProducerDesign", b =>
                {
                    b.Navigation("DesignImages");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("ModelChat");

                    b.Navigation("Offers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Designers.Designer", b =>
                {
                    b.Navigation("DesignVerifications");

                    b.Navigation("DesignerDesigns");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Producers.Producer", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("LicenseVerifications");

                    b.Navigation("ProducerDesigns");

                    b.Navigation("ProducerOffers");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Offers.CustomerPublishedOffer", b =>
                {
                    b.Navigation("ProducerCustomerOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
